'use strict';
const game=new Pacman.Game(),canvas=document.getElementById('game'),ctx=canvas.getContext('2d'),tile=30;
const el=id=>document.getElementById(id);
const descriptions=['Tracks your current position','Aims four tiles ahead of you','Flanks using Blinky’s position','Chases at range, retreats nearby'];
el('agents').innerHTML=game.ghosts.map((g,i)=>`<div class="agent"><div class="avatar" style="background:${g.color}">••</div><div><b>${g.name}</b><small>${descriptions[i]}</small></div><span class="mode" id="mode${i}">${g.strategy.toUpperCase()}</span></div>`).join('');
function toggle(){if(game.state==='running')game.state='paused';else if(game.state==='paused'||game.state==='ready')game.state='running';sync();}
function restart(){game.reset();game.auto=el('auto').checked;sync();draw();}
el('start').onclick=()=>{if(game.state==='over')restart();game.state='running';sync();};el('pause').onclick=toggle;el('restart').onclick=restart;el('auto').onchange=e=>game.auto=e.target.checked;
const directions={ArrowUp:{x:0,y:-1},w:{x:0,y:-1},ArrowDown:{x:0,y:1},s:{x:0,y:1},ArrowLeft:{x:-1,y:0},a:{x:-1,y:0},ArrowRight:{x:1,y:0},d:{x:1,y:0}};
document.addEventListener('keydown',e=>{const d=directions[e.key]||directions[e.key.toLowerCase()];if(d){e.preventDefault();game.wanted=d;}else if(e.code==='Space'&&e.target.tagName!=='BUTTON'&&e.target.tagName!=='INPUT'){e.preventDefault();toggle();}else if(e.key.toLowerCase()==='r')restart();});
document.querySelectorAll('[data-dir]').forEach(b=>b.onclick=()=>game.wanted=directions[{up:'w',down:'s',left:'a',right:'d'}[b.dataset.dir]]);
function sync(){el('score').textContent=String(game.score).padStart(5,'0');el('level').textContent=String(game.level).padStart(2,'0');el('lives').textContent='● '.repeat(game.lives)||'—';el('status').textContent=game.power?`POWER ACTIVE · ${(game.power*.135).toFixed(1)}s`:game.state==='running'?(game.auto?'AUTOPILOT ONLINE':'PLAYER ONLINE'):game.state.toUpperCase();el('pause').textContent=game.state==='paused'?'Resume':'Pause';el('overlay').style.display=game.state==='running'?'none':'flex';el('headline').textContent=game.state==='over'?'GAME OVER':game.state==='paused'?'PAUSED':`LEVEL ${game.level} · READY?`;el('hint').textContent=game.state==='over'?`Final score: ${game.score}. Give the agents another run.`:'Collect every dot. Keep an eye on the agents.';el('start').textContent=game.state==='over'?'Play again →':game.state==='paused'?'Resume →':'Start game →';game.ghosts.forEach((g,i)=>el('mode'+i).textContent=g.cooldown?'RESPAWN':game.power?'FLEE':game.tick%180<35?'SCATTER':g.strategy.toUpperCase());}
function draw(){ctx.clearRect(0,0,630,630);Pacman.MAP.forEach((r,y)=>[...r].forEach((c,x)=>{if(c==='#'){ctx.fillStyle='#102749';ctx.strokeStyle='#24548c';ctx.lineWidth=1;ctx.beginPath();ctx.roundRect(x*tile+3,y*tile+3,tile-6,tile-6,6);ctx.fill();ctx.stroke();}}));for(const k of game.pellets){const [x,y]=k.split(',').map(Number);ctx.fillStyle=game.powers.has(k)?'#ffe56d':'#a8b5cb';ctx.beginPath();ctx.arc(x*tile+15,y*tile+15,game.powers.has(k)?6:2.5,0,Math.PI*2);ctx.fill();}
 if(el('targets').checked&&!game.power){for(const g of game.ghosts){ctx.strokeStyle=g.color+'60';ctx.setLineDash([4,5]);ctx.beginPath();ctx.moveTo(g.x*tile+15,g.y*tile+15);ctx.lineTo(Math.max(15,Math.min(615,g.target.x*tile+15)),Math.max(15,Math.min(615,g.target.y*tile+15)));ctx.stroke();ctx.setLineDash([]);}}
 const p=game.player,angle=Math.atan2(p.dir.y,p.dir.x),mouth=.18+Math.abs(Math.sin(Date.now()/120))*.32;ctx.fillStyle='#ffe56d';ctx.beginPath();ctx.moveTo(p.x*tile+15,p.y*tile+15);ctx.arc(p.x*tile+15,p.y*tile+15,11,angle+mouth,angle+Math.PI*2-mouth);ctx.closePath();ctx.fill();for(const g of game.ghosts){ctx.globalAlpha=g.cooldown?.35:1;ctx.fillStyle=game.power?'#607bff':g.color;const x=g.x*tile+4,y=g.y*tile+4;ctx.beginPath();ctx.arc(x+11,y+10,11,Math.PI,0);ctx.lineTo(x+22,y+23);ctx.lineTo(x+16,y+19);ctx.lineTo(x+11,y+23);ctx.lineTo(x+6,y+19);ctx.lineTo(x,y+23);ctx.closePath();ctx.fill();for(const offset of [7,16]){ctx.fillStyle='white';ctx.beginPath();ctx.ellipse(x+offset,y+10,3.6,4.4,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#111e37';ctx.beginPath();ctx.arc(x+offset+g.dir.x,y+10+g.dir.y,1.8,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}}
let last=0,accumulator=0;function frame(now){if(last)accumulator+=Math.min(now-last,270);last=now;while(accumulator>=135){game.step();accumulator-=135;sync();}draw();requestAnimationFrame(frame);}document.addEventListener('visibilitychange',()=>{if(document.hidden&&game.state==='running'){game.state='paused';sync();}});sync();requestAnimationFrame(frame);
